CREATE TABLE memorization_assessments (
  id CHAR(36) PRIMARY KEY,
  student_id CHAR(36) NOT NULL,
  location_id CHAR(36) NOT NULL,
  assessment_date DATE NOT NULL,
  assessment_type ENUM('NEW_MEMORIZATION', 'MUROJAAH') NOT NULL,
  start_surah_number TINYINT UNSIGNED NOT NULL,
  start_verse_number SMALLINT UNSIGNED NOT NULL,
  end_surah_number TINYINT UNSIGNED NOT NULL,
  end_verse_number SMALLINT UNSIGNED NOT NULL,
  grade ENUM('MUMTAZ', 'JAYYID_JIDDAN', 'JAYYID', 'NEEDS_REVIEW') NOT NULL,
  notes TEXT NULL,
  assessor_user_id CHAR(36) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL,
  CONSTRAINT fk_assessments_student FOREIGN KEY (student_id) REFERENCES students (id) ON DELETE RESTRICT,
  CONSTRAINT fk_assessments_location FOREIGN KEY (location_id) REFERENCES locations (id) ON DELETE RESTRICT,
  CONSTRAINT fk_assessments_start_surah FOREIGN KEY (start_surah_number) REFERENCES quran_surahs (surah_number),
  CONSTRAINT fk_assessments_end_surah FOREIGN KEY (end_surah_number) REFERENCES quran_surahs (surah_number),
  CONSTRAINT fk_assessments_assessor FOREIGN KEY (assessor_user_id) REFERENCES users (id) ON DELETE RESTRICT,
  KEY idx_assessments_student_date (student_id, assessment_date),
  KEY idx_assessments_location (location_id),
  KEY idx_assessments_type (assessment_type),
  KEY idx_assessments_date (assessment_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
